### PR TITLE
Fixes #84, Fixes #33, Fixes #63

### LINKED ISSUE #33: LED Anode should be connected to 3.3v, not 5v.

### LINKED ISSUE #63: CATS HAT v2
Currently our CATS shield is just that - a shield. The next step will be to convert it to a [HAT](https://www.raspberrypi.org/blog/introducing-raspberry-pi-hats/). This means that a connected Pi would be able to identify our CATS HAT and automatically configure the GPIOs and drivers we need for the board.

Please see the [tech specs](https://github.com/raspberrypi/hats).

- [x] #48 Commit CATS Alpha Hardware Designs
- [ ] #57 Solder Repair
- [x] #33 LED Anode 3v
- [ ] #64 ID EEPROM Programming

### LINKED ISSUE #84: First Draft SMD Components
I'd like to start utilizing SMD components in our PCB designs.

I'd recommend utilizing 0805 components or larger at this point in time.

### PR DESCRIPTION
**Pull request by ophilli**
So last night I was talking to Thor - and I told him KiCAD isn't that hard. I said "Hey man, I'll demo it real quick for you!"

And here we are . . .

### CODE REVIEW

**Comment by ophilli** [comment]
@mbgroom Looking forward to your review.

**Comment by ophilli** [comment]
@mbgroom please review or re-assign to @thorbrockman.

**Comment by mbgroom** [comment]
@thorbrockman Please review.

**Review by thorbrockman — APPROVED** [review]
From what I can tell so far, I think it looks good. I can begin finishing the design so we can have it done before the hardware meeting on Thursday.

**Comment by mbgroom** [comment]
PCBs ordered, moving issue to done.

**Pull request merged**
