### PR TITLE
Whitespace Correction & Old Dev Code Removal

### PR DESCRIPTION
**Pull request by ophilli**
I've made a few low-level improvements to get on track for #75.

These include the following:
* Removing old dev code
* Removing G's weird git diff code
* Correcting some weird indentation

### CODE REVIEW

**Comment by ophilli** [comment]
@thorbrockman can you do the code review for this?

**Review by thorbrockman — COMMENTED** [review]
It looks like most things are rearranged or formatted differently. Some files are deleted and I can't test the code to see if it works. @r3cebarnett @gmross could one of you guys review this to see if it works?

**Comment by r3cebarnett** [comment]
I briefly reviewed this (in class) but it seems like most of the stuff was just awkward tabbing, I didn't see any real syntax change. If that's the case than you have my vote, tabbing looks fine.

**Comment by ophilli** [comment]
Sounds good. Can one of you guys, @gmross @r3cebarnett, give approval to merge?

**Review by r3cebarnett — APPROVED** [review]

**Pull request merged**
