### PR TITLE
deleted rpi command that makes error

### PR DESCRIPTION
**Pull request by gacosta1**

### CODE REVIEW

**Review by ophilli — APPROVED** [review]
I'm approving this so that other team members can work based off of what you've got going on.

I also shifted you to the devel branch - to clarify that the code base isn't ready for production yet.

**Comment by gacosta1** [comment]
Awesomee Thanks!!!

Giandre Acosta
Clemson University 17'
B.S. Computer Science

**Comment by ophilli** [comment]
@gacosta1 Not a problem! You should be able to merge the commit after signing the CLA.

Please let me know if you have any concerns with the language associated with the CLA.

**Comment by gacosta1** [comment]
For the part where it says: "Corporate Contributor Information" do i put an
"N/A" cause Im not employed as a software develop nor is my employer in the
business of developing software. Im just a student trying to gain access lol

Giandre Acosta
Clemson University 17'
B.S. Computer Science

**Comment by ophilli** [comment]
@gacosta1 Yep - you can just put a N/A!

**Pull request merged**
