### PR TITLE
Hardware information

### PR DESCRIPTION
**Pull request by Sabare3**
Attached Schematics and Diagrams.

### CODE REVIEW

**Review by gacosta1 — APPROVED** [review]

**Comment by ophilli** [comment]
@Sabare3 Please sign the [CLA for CATS](https://www.clahub.com/agreements/clemsonMakerspace/CATS) and give me your thoughts.

Then I will need you to merge in the latest changes from devel before we can merge your pull request.

**Comment by gacosta1** [comment]
@Sabare3 Whenever you're signing the [CLA](https://www.clahub.com/agreements/clemsonMakerspace/CATS), once you get to the "Corporate Contributor Information" you can just put N/A =D

**Comment by ophilli** [comment]
@Sabare3 Please sign the [CLA ](https://www.clahub.com/agreements/clemsonMakerspace/CATS) and merge in the latest changes from devel.

**Comment by ophilli** [comment]
Closed due to non-compliance.

**Pull request closed without merging**
